export enum OrderStatus {
  AWAITING_PAYMENY = 'AWAITING_PAYMENY',
  AWAITING_SHIPMENT = 'AWAITING_SHIPMENT',
  ALMOST_SHIPPING = 'ALMOST_SHIPPING',
  SHIPPED = 'SHIPPED',
  IN_TRANSIT = 'IN_TRANSIT',
  COMPLETED = 'COMPLETED',
  CANCELED = 'CANCELED',
}
